- name: Collect OneView information
  hosts: all
  gather_facts: no
  vars:
    oneview_host: 10.88.160.205
    oneview_username: Infra_admin
    oneview_password: Oneview!098
    oneview_validate_certs: no
    delegate_to: localhost
    config: /root/.ansible/collections/ansible_collections/hpe/oneview/config.json
  tasks:
    - name: Gather facts about all Enclosures
      oneview_enclosure_facts:
        config: "{{ config }}"
      delegate_to: localhost

    - debug: var=enclosures

    - name: Gather paginated, filtered and sorted facts about Enclosures
      oneview_enclosure_facts:
        config: "{{ config }}"
        params:
          start: 0
          count: 3
          sort: 'name:descending'
          filter: 'status=OK'

    - debug: var=enclosures

    - name: Gather facts about an Enclosure by name
      oneview_enclosure_facts:
        config: "{{ config }}"
        name: "{{ contents.enclosure.enclosure_name }}"
      delegate_to: localhost

    - debug: var=enclosures
